name: "graphql-training"

services:
  db:
    image: "postgres:latest"
    env_file: .env
    volumes:
      - "pgdata:/var/lib/postgresql/pgdata"
      - "./DB_config.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d graphql_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    env_file: .env
    ports:
      - '8080:8080'
    restart: "no"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
